CREATE TABLE IF NOT EXISTS rsvp_invite_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  max_guests INTEGER NOT NULL CHECK (max_guests BETWEEN 1 AND 10),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS rsvp_invite_links_token_active_idx
  ON rsvp_invite_links (token)
  WHERE deleted_at IS NULL AND is_active = TRUE;

ALTER TABLE rsvp_invite_links ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE rsvp_invite_links IS
  'Admin-created RSVP links with server-enforced party-size limits.';
